import os

# Auxiliary functions to parse paths defined in config
# PLACEHOLDER?
def get_base_path_selectorinputs( subconfig_path, subconfig_dtype_full, dtype_full): 
  # subconfig_path is config["Selector"]["dst_common_path"] or config["Selector"]["scores_common_path"]
  # subconfig_dtype_full is config["ResponseFunction"]['sources_dtype_full']
  if isinstance(subconfig_path, dict):
    for source_iter, dtype_full_iter in subconfig_dtype_full.items():
      # "Invert' subconfig_dtype_full to find source from dtype_full
      if dtype_full == dtype_full_iter:
        if source_iter in subconfig_path.keys():
          return subconfig_path[source_iter]
        else:
          print("ERROR: Source is", source_iter, " but it is not present in Selector config!")
  elif isinstance(subconfig_path, str):
    return subconfig_path
  else:
    print("ERROR: Cannot derive dst/score path from config and dtype_full:", dtype_full, subconfig_path)
  return "" # ERROR!

def get_selectorinput_dst(dtype_full):
  base_path = get_base_path_selectorinputs(
      config["Selector"]["dst_common_path"],
      config["ResponseFunction"]['sources_dtype_full'],
      dtype_full
  )
  return os.path.join(base_path, "KM3NeT_{detid}_{run}.{dtype_full}.{version}.root")

def get_selectorinput_scores(dtype_full):
  base_path = get_base_path_selectorinputs(
      config["Selector"]["scores_common_path"],
      config["ResponseFunction"]['sources_dtype_full'],
      dtype_full
  )
  return os.path.join(base_path, "ScoreTree_PID_KM3NeT_{detid}_{run}.{dtype_full}.{version}.scoretree.root")


# RULES
rule apply_selections:
    """
    This rule applies the selector function.
    PLACEHOLDER: we need an earlier rule to acquire the input dst and score files.
    """
    output:
        fname = temp("Selector/{detid}/unmerged/KM3NeT_{detid}_{run}.{dtype_full}.{version}.selection.root")
    input:
        ifile_dst = lambda wildcards:  get_selectorinput_dst(wildcards.dtype_full),
        ifile_scores = lambda wildcards:  get_selectorinput_scores(wildcards.dtype_full)
    params:
        scores_ttreename=lambda wildcards: get_detector_config(config["Selector"], wildcards.detid)["scores_ttreename"], # Name of the score TTree
        selector_cut=lambda wildcards: get_detector_config(config["Selector"], wildcards.detid)["cut"] # Preliminary cut
    container:
        config["ResponseFunction"]["singularity"]
    log:
        "logs/Selector/{detid}/unmerged/KM3NeT_{detid}_{run}.{dtype_full}.{version}.selection.log"
    benchmark:
        "benchmarks/Selector/{detid}/unmerged/KM3NeT_{detid}_{run}.{dtype_full}.{version}.selection.tsv"
    shell:
        """
        {{
        source /IRF/setenv.sh

        /IRF/Selector/SelectorFromJSON -i "{input.ifile_dst}" -f "{input.ifile_scores},{params.scores_ttreename}" -c "{params.selector_cut}" -o "{output.fname}"
        }} > {log} 2>&1 | tee {log}
        """

def get_selectoroutputs_detid(wildcards):
    return expand( "Selector/{detid}/unmerged/KM3NeT_{detid}_{run}.{dtype_full}.{version}.selection.root",
        run = extended_config['detids_runs_to_do'][wildcards.detid],
        **wildcards
    )

ruleorder: copy_selection_to_workdir > merge_selector_files_detid

rule merge_selector_files_detid:
    """
    This rule will merge the same file types generated by the selector.
    """
    output:
        merged_file = "Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.root"
    input:
        selection = get_selectoroutputs_detid
    container:
        config["ResponseFunction"]["singularity"]
    log:
        "logs/Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.log"
    benchmark:
        "benchmarks/Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.tsv"
    shell:
        """
        {{
        hadd -f {output.merged_file} {input.selection}
        }} > {log} 2>&1 | tee {log}
        """

rule copy_selection_to_workdir:
    """
    This rule will copy merged selector files from an external path if provided.
    """
    localrule: True
    output:
        "Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.root"
    input:
        lambda wildcards: "{output_common_path}/Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.root".format(output_common_path = config["Selector"]["output_common_path"], **wildcards)
    log:
        "logs/Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.log"
    benchmark:
        "benchmarks/Selector/{detid}/merged/KM3NeT_{detid}.{dtype_full}.{version}.selection.tsv"
    shell:
        """
        {{
	      cp {input} {output}
        }} > {log} 2>&1 | tee {log}
        """
